version: '2.1'
services:
  db:
    image: mysql:5.7.29
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'product_component'
    volumes:
      - my-db:/var/lib/mysql

  product_component:
    build: .
    volumes:
      - ${PWD}/:/src/app
    ports:
      - "8000:3002"
    depends_on:
      - db
volumes:
  my-db: {}